
export { Icon1 } from './Icon1';
export { Icon2 } from './Icon2';
export { Icon3 } from './Icon3';
export { Icon4 } from './Icon4';
export { Icon5 } from './Icon5';
export { Icon6 } from './Icon6';
export { default as Icon7 } from './Icon7';
export { default as Icon8 } from './Icon8';
export { OuterCircle } from './OuterCircle';
export { InnerCircle } from './InnerCircle';
export { PuzzleIcon } from './PuzzleIcon';
export { ArrowDown } from './ArrowDown';
export { CurveArrows } from './CurveArrows';
export { Lightbulb } from './Lightbulb';
export { WorkspaceBuilding } from './WorkspaceBuilding';
export { ExcellenceChart } from './ExcellenceChart';
export { ExcellenceGear } from './ExcellenceGear';
export { GlowDot } from './GlowDot';
export { CultureCircle } from './CultureCircle';
export { Link } from './Link';
export { default as StrategicInsights } from './StrategicInsights';
export { default as Twitter } from './Twitter';
export { default as SnapChat } from './SnapChat';
export { default as LinkedIn } from './LinkedIn';
export { default as Instagram } from './Instagram';
export { default as Facebook } from './Facebook';
export { default as Shopping } from './Shopping';
export { default as NurturingFollow } from './NurturingFollow';
export { default as Seo } from './Seo';
export { default as Rate } from './Rate';
export { default as SaasAi } from './SaasAi';
export { default as Switch } from './Switch';
export { default as HumanCentricBpo } from './HumanCentricBpo';
export { default as DataDrivenInsights } from './DataDrivenInsights';
export { default as DigitalAutomationSaas } from './DigitalAutomationSaas';
export { default as AboutUs } from './AboutUs';
export { default as UnveilingDrc } from './UnveilingDrc';
export { default as DataDrivenInsightsBig } from './DataDrivenInsightsBig';
export { default as DigitalAutomationSaasBig } from './DigitalAutomationSaasBig';
export { default as CostOptimization } from './CostOptimization';
export { default as BrainConnection } from './BrainConnection';
export { default as GroupPeople } from './GroupPeople';
export { default as AccessTopTalent } from './AccessTopTalent';
export { default as TechnologyIntegration } from './TechnologyIntegration';
export { default as TopArrow } from './TopArrow';
export { default as BottomLeftArrow } from './BottomLeftArrow';
export { default as BottomRightArrow } from './BottomRightArrow';
export { default as StackingCart } from './StackingCart';
export { default as StackingSetting } from './StackingSetting';
export { default as StackingBackdropIcon } from './StackingBackdropIcon';
export { default as BrainBig } from './BrainBig';
export { default as Ai } from './Ai'; 
export { default as Cost } from './Cost';
export { default as Group } from './Group';
export { default as Global } from './Global';
export { default as Internet } from './Internet';
export { default as Virus } from './Virus';
export { default as Light } from './Light';
export { default as HistoryTopLeftIcon } from './HistoryTopLeftIcon';
export { default as InsightsTopLeftIcon } from './InsightsTopLeftIcon';
export { default as HistoryBottomLeftIcon } from './HistoryBottomLeftIcon';
export { default as InsightsTopRightIcon } from './InsightsTopRightIcon';
export { default as InsightsBottomLeftIcon } from './InsightsBottomLeftIcon';
